-- Esquema inicial del sistema de correspondencia.
-- Corresponde al estado del esquema tras las iteraciones 1-4 (HU-01 a HU-08).

-- =============================================================================
-- Tabla: area
-- =============================================================================
CREATE TABLE area (
    id      BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre  VARCHAR(80)  NOT NULL,
    activo  BOOLEAN      NOT NULL,
    CONSTRAINT uk_area_nombre UNIQUE (nombre)
);

-- =============================================================================
-- Tabla: usuario
-- =============================================================================
CREATE TABLE usuario (
    id                        BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username                  VARCHAR(12)   NOT NULL,
    nombre_completo           VARCHAR(50)   NOT NULL,
    email                     VARCHAR(120)  NOT NULL,
    password_hash             VARCHAR(255)  NOT NULL,
    rol                       VARCHAR(20)   NOT NULL,
    area_id                   BIGINT        NOT NULL,
    bloqueada                 BOOLEAN       NOT NULL,
    intentos_fallidos         INTEGER       NOT NULL,
    debe_cambiar_password     BOOLEAN       NOT NULL,
    creado_en                 TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_usuario_username CHECK (char_length(username) BETWEEN 1 AND 12),
    CONSTRAINT usuario_username_unique UNIQUE (username),
    CONSTRAINT usuario_email_unique UNIQUE (email),
    CONSTRAINT usuario_rol_check CHECK (rol IN ('ADMIN', 'SUPERVISOR', 'RECEPCIONISTA', 'MENSAJERO')),
    CONSTRAINT fk_usuario_area FOREIGN KEY (area_id) REFERENCES area (id)
);

-- =============================================================================
-- Tabla: secuencia_folio
-- =============================================================================
CREATE TABLE secuencia_folio (
    anio           INTEGER  NOT NULL PRIMARY KEY,
    ultimo_numero  INTEGER  NOT NULL
);

-- =============================================================================
-- Tabla: correspondencia
-- =============================================================================
CREATE TABLE correspondencia (
    id                       BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    folio                    VARCHAR(20)   NOT NULL,
    fecha_recepcion          TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    remitente                VARCHAR(120)  NOT NULL,
    tipo_remitente           VARCHAR(10)   NOT NULL,
    asunto                   VARCHAR(200)  NOT NULL,
    tipo                     VARCHAR(15)   NOT NULL,
    prioridad                VARCHAR(10)   NOT NULL,
    area_destino_id          BIGINT        NOT NULL,
    observaciones            VARCHAR(500),
    estado                   VARCHAR(15)   NOT NULL,
    recepcionado_por_id      BIGINT        NOT NULL,
    mensajero_id             BIGINT,
    fecha_asignacion         TIMESTAMP(6) WITH TIME ZONE,
    fecha_entrega            TIMESTAMP(6) WITH TIME ZONE,
    nombre_recibe            VARCHAR(120),
    observaciones_entrega    VARCHAR(500),
    motivo_anulacion         VARCHAR(500),
    anulado_en               TIMESTAMP(6) WITH TIME ZONE,
    anulado_por_id           BIGINT,
    motivo_archivo           VARCHAR(500),
    archivado_en             TIMESTAMP(6) WITH TIME ZONE,
    archivado_por_id         BIGINT,
    creado_en                TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT correspondencia_folio_unique UNIQUE (folio),
    CONSTRAINT correspondencia_estado_check CHECK (estado IN ('RECIBIDA', 'EN_TRAMITE', 'ENTREGADA', 'ARCHIVADA', 'ANULADA')),
    CONSTRAINT correspondencia_tipo_check CHECK (tipo IN ('OFICIO', 'CIRCULAR', 'MEMO', 'INVITACION', 'OTRO')),
    CONSTRAINT correspondencia_tipo_remitente_check CHECK (tipo_remitente IN ('EXTERNO', 'INTERNO')),
    CONSTRAINT correspondencia_prioridad_check CHECK (prioridad IN ('NORMAL', 'URGENTE')),
    CONSTRAINT fk_correspondencia_area_destino FOREIGN KEY (area_destino_id) REFERENCES area (id),
    CONSTRAINT fk_correspondencia_recepcionado_por FOREIGN KEY (recepcionado_por_id) REFERENCES usuario (id),
    CONSTRAINT fk_correspondencia_mensajero FOREIGN KEY (mensajero_id) REFERENCES usuario (id),
    CONSTRAINT fk_correspondencia_anulado_por FOREIGN KEY (anulado_por_id) REFERENCES usuario (id),
    CONSTRAINT fk_correspondencia_archivado_por FOREIGN KEY (archivado_por_id) REFERENCES usuario (id)
);

CREATE UNIQUE INDEX idx_correspondencia_folio ON correspondencia (folio);
CREATE INDEX idx_correspondencia_estado ON correspondencia (estado);
CREATE INDEX idx_correspondencia_fecha ON correspondencia (fecha_recepcion);
